linters:
  enable:
    - govet
    - gofmt
    - goimports
    - misspell
  disable:
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - revive
  settings:
    govet:
      shadow: true
